from tkinter import *
def clicked():
    global t
    t=txt.get()
    wnd.destroy()
wnd=Tk()
wnd.title("Exercise №3 of the 11th chapter")
wnd.geometry("330x150")
wnd.resizable(False, False)
fnt=("Calibri",13,"bold")
t=""
lbl=Label(master=wnd,text="How old are you?")
lbl.configure(font=fnt)
lbl.place(x=10,y=20)
txt=Entry(master=wnd, width=34, font=fnt)
txt.place(x=10, y=50)
btn_1=Button(master=wnd, text="Ok")
btn_2=Button(master=wnd, text="Cancel")
btn_1.configure(font=fnt)
btn_1.configure(command=clicked)
btn_2.configure(font=fnt)
btn_2.configure(command=clicked)
btn_1.place(x=40, y=80, width=100, height=30)
btn_2.place(x=165, y=80, width=100, height=30)
wnd.mainloop()
if t!="":
    msg=Tk()
    msg.title("Year of Birth")
    msg.geometry("340x100")
    msg.resizable(False, False)
    lbl=Label(master=msg, text="We calculated your year of the birth: "+str(2024-int(t))+"!", relief=GROOVE)
    lbl.configure(font=fnt)
    lbl.place(x=10, y=10, height=40, width=320)
    btn=Button(master=msg, text="Ok")
    btn.configure(font=fnt)
    btn.configure(command=msg.destroy)
    btn.place(x=110, y=60, width=100, height=30)
    msg.mainloop()