from tkinter import *
def updated_label(*args):
    lbl.configure(text=txt.get())
def clicked():
    txt.delete(0, END)
    lbl.configure(text="")
wnd=Tk()
wnd.title("Exercise №4 of the 11th chapter")
wnd.geometry("330x150")
wnd.resizable(False, False)
fnt=("Arial",13,"bold","italic")
txt=Entry(master=wnd, width=34, font=fnt)
txt.place(x=10, y=50)
lbl = Label(master=wnd, font=fnt, text="")
lbl.place(x=10, y=20)
txt.bind("<KeyRelease>", updated_label)
btn_1=Button(master=wnd, text="Clear")
btn_2=Button(master=wnd, text="Cancel")
btn_1.configure(font=fnt)
btn_1.configure(command=clicked)
btn_2.configure(font=fnt)
btn_2.configure(command=wnd.destroy)
btn_1.place(x=40, y=80, width=100, height=30)
btn_2.place(x=165, y=80, width=100, height=30)
wnd.mainloop()